name = "aiken-lang/merkle-patricia-forestry"
version = "1.0.0"
license = "MPL-2.0"
description = "Aiken contracts for project 'aiken-lang/merkle-patricia-forestry'"

[repository]
user = "aiken-lang"
project = "merkle-patricia-forestry"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"
